// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-solutions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.24.2";

// src/lib/mcp/data.ts
var SITE_URL = "https://s2mgt.com";
var solutions = [
  { title: "Disaster Recovery", category: "Data Protection", description: "Comprehensive DR planning and orchestration.", path: "/solutions/opentext-carbonite-availability" },
  { title: "Server Migration", category: "Data Protection", description: "Seamless any-to-any server migrations.", path: "/solutions/opentext-carbonite-migrate" },
  { title: "Disaster Recovery Orchestration", category: "Data Protection", description: "Automated DR workflow orchestration.", path: "/solutions/disaster-recovery-orchestration" },
  { title: "Server Migration Orchestration", category: "Data Protection", description: "Automated server migration workflows.", path: "/solutions/server-migration-orchestration" },
  { title: "Endpoint Cloud Backup", category: "Data Protection", description: "Cloud-based endpoint protection.", path: "/solutions/endpoint-backup" },
  { title: "Servers Cloud Backup", category: "Data Protection", description: "Server backup and replication in the cloud.", path: "/solutions/saas-backup" },
  { title: "On Prem Backup", category: "Data Protection", description: "Local, on-premises backup solutions.", path: "/solutions/onprem-backup" },
  { title: "Server Backup", category: "Data Protection", description: "OpenText server backup and replication.", path: "/solutions/OpenText-Server-Backup" },
  { title: "Email Archiving", category: "Data Protection", description: "Email compliance and continuity archiving.", path: "/solutions/email-archiving" },
  { title: "Container Migration", category: "Data Protection", description: "Kubernetes and OpenShift cluster migration.", path: "/solutions/container-migration" },
  { title: "Cloud Migration & Modernization", category: "Data Protection", description: "Agentless migration and OS modernization across multi-cloud environments.", path: "/solutions/cloud-migration" },
  { title: "Servers and Data Protection", category: "Cybersecurity", description: "Insider threat protection and access control.", path: "/solutions/servers-data-protection" },
  { title: "Endpoint Protection with EDR", category: "Cybersecurity", description: "Comprehensive endpoint security with detection and response.", path: "/solutions/endpoint-protection" },
  { title: "Ransomware Protection", category: "Cybersecurity", description: "Advanced ransomware defense systems.", path: "/solutions/ransomware-protection" },
  { title: "MDR", category: "Cybersecurity", description: "Managed Detection and Response.", path: "/solutions/mdr" },
  { title: "Security Awareness", category: "Cybersecurity", description: "User security awareness training.", path: "/solutions/security-awareness" },
  { title: "Email Protection", category: "Cybersecurity", description: "Email threat protection.", path: "/solutions/email-protection" },
  { title: "Email Encryption", category: "Cybersecurity", description: "Secure, encrypted email communications.", path: "/solutions/email-encryption" }
];
var vendors = [
  { name: "OpenText", focus: "Core Data Protection Platform", tagline: "Enterprise-grade data protection, availability, and secure cloud solutions.", offerings: ["Data Protection - Availability & Migrate", "Secure Cloud Suite - Cloud-to-Cloud Backup", "Email Continuity & Archiving", "Endpoint & Threat Protection"], path: "/vendors/opentext" },
  { name: "TDS", focus: "Orchestration & IT Visibility", tagline: "Orchestration and automation platform that streamlines migration and disaster recovery while accelerating IT operations.", offerings: ["IT Discovery & Asset Management", "Dependency Mapping & Visualization", "Migration Wave Planning", "DR Orchestration & Reporting"], path: "/vendors/tds" },
  { name: "appCURE", focus: "Application Modernization", tagline: "Complete application transformation and modernization platform.", offerings: ["Capture - Application Assessment", "Studio - App Repackaging", "Runtime - Secure Environments", "DMT - Desktop Modernization"], path: "/vendors/appcure" },
  { name: "NAKIVO", focus: "Backup & Recovery", tagline: "Fast, affordable data protection for virtual, cloud, and hybrid environments.", offerings: ["VM Backup & Recovery for VMware, Hyper-V, Nutanix AHV, Proxmox VE", "Cloud data protection to Amazon S3, Azure, Wasabi", "Microsoft 365 backup", "Physical server and file share backup"], path: "/vendors/nakivo" },
  { name: "Arrosoft", focus: "Advanced Cybersecurity & Threat Protection", tagline: "Protecting against insider threats and ransomware attacks.", offerings: ["Stealth - Kernel-level protection & data hiding", "AirGap - Immutable backup vault protection", "Driver-layer isolation", "Multi-factor authentication / zero trust"], path: "/vendors/arrosoft" },
  { name: "RiverMeadow", focus: "Automated Cloud Migration", tagline: "Automated workload migration of Windows and Linux servers to any cloud with minimal downtime.", offerings: ["Automated cloud migration (Collect-Convert-Deploy)", "Agentless, rapid and secure migration", "Fixed-price per-instance service", "Lift & optimize: OS upgrades, SQL to AWS RDS"], path: "/vendors/rivermeadow" },
  { name: "CloudCasa", focus: "Kubernetes Data Protection & Migration", tagline: "Backup and disaster recovery for Kubernetes environments across multi-cloud and hybrid infrastructures.", offerings: ["Kubernetes backup & recovery for any CNCF distribution", "Multi-cloud management from a single dashboard", "Application migration between distributions and clouds", "SaaS or self-hosted with immutable backups"], path: "/vendors/cloudcasa" }
];
var services = [
  { title: "Strategic Consulting", items: ["Strategic technology planning & roadmapping", "Vendor-neutral assessments & recommendations", "Custom development roadmaps", "Risk analysis & mitigation strategies", "Business continuity planning"] },
  { title: "Solutions Architecture", items: ["Cloud transformation design & strategy", "Enterprise cybersecurity architecture", "Disaster recovery & backup planning", "Infrastructure modernization", "Future-proof scalable solutions"] },
  { title: "Professional Services", items: ["Full project management & delivery", "Milestone-driven project execution", "Comprehensive testing & validation", "Knowledge transfer & training", "On-time, on-budget execution"] },
  { title: "Service Level Agreements", items: ["Customizable service level tiers", "Guaranteed recovery time objectives", "24/7 incident response protocols", "Regular testing & validation cycles", "Clear escalation procedures"] },
  { title: "App Modernization", items: ["Legacy system assessment & planning", "Detailed dependency mapping", "Minimal downtime migration strategies", "Multi-platform compatibility support", "Risk-managed modernization approach"] }
];
var contact = {
  email: "admin@s2mgt.com",
  offices: [
    { country: "United Arab Emirates", address: "Publishing Pavilion by Tecom Group - Office 208 - Me'aisem First - Dubai Production City - Dubai", phone: "+971 4 434 2221" },
    { country: "Saudi Arabia", phone: "+966 55 084 6532" }
  ],
  contactPage: "/contact"
};

// src/lib/mcp/tools/list-solutions.ts
var list_solutions_default = defineTool({
  name: "list_solutions",
  title: "List solutions",
  description: "List S2 Management Solutions' data protection and cybersecurity solutions, with descriptions and page URLs.",
  inputSchema: {
    category: z.enum(["Data Protection", "Cybersecurity", "All"]).default("All").describe("Filter solutions by category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const rows = solutions.filter((s) => category === "All" || s.category === category).map((s) => ({ ...s, url: SITE_URL + s.path }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { solutions: rows }
    };
  }
});

// src/lib/mcp/tools/get-solution.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.24.2";
var get_solution_default = defineTool2({
  name: "get_solution",
  title: "Get solution details",
  description: "Get details for one S2 Management Solutions solution by name (case-insensitive, partial match allowed).",
  inputSchema: { name: z2.string().trim().min(1).describe("Solution name, e.g. 'Ransomware Protection'.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ name }) => {
    const q = name.toLowerCase();
    const match = solutions.find((s) => s.title.toLowerCase() === q) ?? solutions.find((s) => s.title.toLowerCase().includes(q));
    if (!match) {
      throw new ToolError(
        `No solution matches "${name}". Known solutions: ${solutions.map((s) => s.title).join(", ")}.`
      );
    }
    const result = { ...match, url: SITE_URL + match.path };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { solution: result }
    };
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.24.2";
var list_vendors_default = defineTool3({
  name: "list_vendors",
  title: "List technology partners",
  description: "List the technology vendors and partners S2 Management Solutions works with, their focus areas and offerings.",
  inputSchema: { name: z3.string().trim().optional().describe("Optional vendor name filter (partial, case-insensitive).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ name }) => {
    const q = name?.toLowerCase();
    const rows = vendors.filter((v) => !q || v.name.toLowerCase().includes(q)).map((v) => ({ ...v, url: v.path.startsWith("http") ? v.path : SITE_URL + v.path }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { vendors: rows }
    };
  }
});

// src/lib/mcp/tools/get-company-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_company_info_default = defineTool4({
  name: "get_company_info",
  title: "Get company and contact info",
  description: "Get S2 Management Solutions' service capabilities, office locations and public contact details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "S2 Management Solutions",
      summary: "S2 Management Solutions is a Dubai-based technology consultancy delivering data protection, disaster recovery, cloud migration and cybersecurity solutions across the Middle East.",
      website: SITE_URL,
      services,
      contact: { ...contact, contactPageUrl: SITE_URL + contact.contactPage }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "s2-mgt-website-rebuild",
  title: "s2-mgt-website-rebuild",
  version: "0.1.0",
  instructions: "Public tools for the S2 Management Solutions website. Use `list_solutions` and `get_solution` for data protection and cybersecurity offerings, `list_vendors` for technology partners, and `get_company_info` for services, offices and contact details.",
  // @ts-expect-error upstream @lovable.dev/mcp-js types outputSchema as non-optional under exactOptionalPropertyTypes; tools without outputSchema are valid at runtime
  tools: [list_solutions_default, get_solution_default, list_vendors_default, get_company_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
